#name, main, version and api are required
name: Levels
main: levels.MainClass
#remember version and api is string, don't write it like this: 1.0.0, or there will be an exception
version: "1.0.0"
api: ["1.0.0"]

load: POSTWORLD
author: GutlessMango631
description: Level up!
website: https://github.com/Nukkit/ExamplePlugin
commands:
  level:
    description: Shows your level
    usage: "/level"
    permission: exampleplugin.command.example
permissions:
  exampleplugin.command.example:
    description: "Allows the user to run the example command"
    default: true